// Job receipts — proof-of-work for Muster bots.
//
// Every settled task can produce a receipt: who did the job, what it was,
// how long it took, what it cost in tokens, and the bot's final word.
// Deliberately a pure composer (no I/O) so the format is pinned by tests
// and identical from every caller — API, chat card, share text.

export interface ReceiptInput {
  botName: string;
  taskTitle: string;
  createdAt: number;
  finishedAt: number;
  usage?: { input: number; output: number; costUsd: number | null; turns: number };
  /** The bot's last authored message, if any. */
  finalWord?: string | null;
  /** Deterministic post-run findings (server/receipt-findings.ts). */
  findings?: string[];
}

export interface JobReceipt {
  version: 1;
  bot: string;
  job: string;
  startedAt: string;
  durationMs: number;
  durationHuman: string;
  turns: number;
  tokensIn: number;
  tokensOut: number;
  costUsd: number | null;
  result: "done" | "no-reply";
  summary: string;
  /** Optional: receipts shared before findings existed carry none, and
   * their stored signatures stay valid — additive fields only. */
  findings?: string[];
}

const MAX_SUMMARY_CHARS = 280;

export function formatDuration(ms: number): string {
  if (!Number.isFinite(ms) || ms < 0) return "—";
  const s = Math.round(ms / 1000);
  if (s < 60) return `${s}s`;
  const m = Math.floor(s / 60);
  if (m < 60) return `${m}m ${s % 60}s`;
  const h = Math.floor(m / 60);
  return `${h}h ${m % 60}m`;
}

export function buildReceipt(input: ReceiptInput): JobReceipt {
  const durationMs = Math.max(0, input.finishedAt - input.createdAt);
  const rawSummary = (input.finalWord ?? "").trim();
  // SAFETY: slice after trim; collapse newlines so the receipt stays one card.
  const summary = rawSummary.replace(/\s+/g, " ").slice(0, MAX_SUMMARY_CHARS);
  return {
    version: 1,
    bot: input.botName,
    job: input.taskTitle,
    startedAt: new Date(input.createdAt).toISOString(),
    durationMs,
    durationHuman: formatDuration(durationMs),
    turns: input.usage?.turns ?? 0,
    tokensIn: input.usage?.input ?? 0,
    tokensOut: input.usage?.output ?? 0,
    costUsd: input.usage?.costUsd ?? null,
    result: rawSummary ? "done" : "no-reply",
    summary,
    // JsonObject forbids undefined values — spread conditionally.
    ...(input.findings && input.findings.length > 0 ? { findings: input.findings } : {}),
  };
}

/** Plain-text rendering — what "Copy receipt" puts on the clipboard and
 * what a bot pastes when asked to prove its work somewhere. */
export function renderReceiptText(r: JobReceipt): string {
  const cost = r.costUsd !== null ? `$${r.costUsd.toFixed(4)}` : "n/a";
  return [
    `🧾 Job receipt — ${r.job}`,
    `Bot: ${r.bot}`,
    `Started: ${r.startedAt}`,
    `Duration: ${r.durationHuman} · Turns: ${r.turns}`,
    `Tokens: ${r.tokensIn.toLocaleString()} in / ${r.tokensOut.toLocaleString()} out · Cost: ${cost}`,
    ``,
    r.summary || "(no final reply recorded)",
    ...(r.findings && r.findings.length > 0
      ? ["", `Findings: ${r.findings.join(" · ")}`]
      : ["", "Findings: none — clean run"]),
    ``,
    `Generated by Muster — bots with receipts.`,
  ].join("\n");
}
