// Wrapped — Muster's weekly review, a Spotify-Wrapped-style shareable
// summary of what your fleet did this week. Pure composer: no I/O, format
// pinned by tests. Feeds the future PNG export + Monday routine.

export interface WrappedBot {
  name: string;
  /** settled turns this week */
  turns: number;
  tokensIn: number;
  tokensOut: number;
  costUsd: number | null;
}

export interface WrappedInput {
  bots: WrappedBot[];
  /** ISO date for "today" — injectable so tests are deterministic. */
  today?: string;
}

export interface WrappedCard {
  weekOf: string;
  totalTurns: number;
  totalTokens: number;
  costUsd: number | null;
  topBot: string | null;
  activeBots: number;
  headline: string;
}

function mondayOf(iso: string): string {
  const d = new Date(iso);
  const day = d.getUTCDay() || 7;
  d.setUTCDate(d.getUTCDate() - (day - 1));
  return d.toISOString().slice(0, 10);
}

const HEADLINES = [
  "Your fleet put in work",
  "The team showed up",
  "Quietly relentless",
  "Machines don't take Fridays off",
];

export function buildWrapped(input: WrappedInput): WrappedCard {
  const today = input.today ?? new Date().toISOString();
  const weekOf = mondayOf(today);
  const totalTurns = input.bots.reduce((s, b) => s + b.turns, 0);
  const totalTokens = input.bots.reduce((s, b) => s + b.tokensIn + b.tokensOut, 0);
  const costs = input.bots.map((b) => b.costUsd).filter((c) => c !== null);
  // SAFETY: filter above guarantees numbers only; sum is safe.
  const costUsd = costs.length ? costs.reduce((s, c) => s + (c ?? 0), 0) : null;
  const activeBots = input.bots.filter((b) => b.turns > 0);
  const top = [...activeBots].sort((a, b) => b.turns - a.turns)[0];
  const headline =
    totalTurns === 0
      ? "A quiet week on the muster"
      : HEADLINES[totalTurns % HEADLINES.length]!;
  return {
    weekOf,
    totalTurns,
    totalTokens,
    costUsd,
    topBot: top?.name ?? null,
    activeBots: activeBots.length,
    headline,
  };
}

/** Plain-text rendering — what "Copy my Wrapped" puts on the clipboard and
 * what the Monday routine posts into chat. */
export function renderWrappedText(w: WrappedCard): string {
  const cost = w.costUsd !== null ? `$${w.costUsd.toFixed(2)}` : "n/a";
  const lines = [
    `📊 Muster Wrapped — week of ${w.weekOf}`,
    `"${w.headline}"`,
    ``,
    `Turns: ${w.totalTurns.toLocaleString()}`,
    `Tokens: ${w.totalTokens.toLocaleString()}`,
    `Spend: ${cost}`,
  ];
  if (w.topBot) lines.push(`Top teammate: ${w.topBot}`);
  if (w.activeBots > 0) lines.push(`Active teammates: ${w.activeBots}`);
  lines.push("", `Generated by Muster — bots with receipts.`);
  return lines.join("\n");
}
